"use client";

import { useEffect, useMemo, useState } from "react";
import type { BaseNode, BaseSpace } from "./CognitiveBasePage";

type Version = { id: string; spaceId: string; versionNumber: number; title: string; summary: string; snapshotJson: string; sourceRecordIdsJson: string; status: string; createdAt: string };
type RecordRef = { id: string; title: string; source: string };

export function BaseVersionHistory() {
  const [spaces, setSpaces] = useState<BaseSpace[]>([]); const [versions, setVersions] = useState<Version[]>([]); const [records, setRecords] = useState<RecordRef[]>([]); const [spaceId, setSpaceId] = useState(""); const [selectedId, setSelectedId] = useState(""); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/bases"); const data = await response.json(); if (response.ok) { setSpaces(data.spaces || []); setVersions(data.versions || []); setRecords(data.records || []); const firstSpace = spaceId || data.spaces?.[0]?.id || ""; setSpaceId(firstSpace); const firstVersion = (data.versions || []).find((item: Version) => item.spaceId === firstSpace); if (!selectedId && firstVersion) setSelectedId(firstVersion.id); } }
  useEffect(() => { fetch("/api/bases").then((response) => response.ok ? response.json() : null).then((data) => { if (!data) return; setSpaces(data.spaces || []); setVersions(data.versions || []); setRecords(data.records || []); const firstSpace = data.spaces?.[0]?.id || ""; setSpaceId(firstSpace); const firstVersion = (data.versions || []).find((item: Version) => item.spaceId === firstSpace); if (firstVersion) setSelectedId(firstVersion.id); }).catch(() => undefined); }, []);
  const currentVersions = useMemo(() => versions.filter((item) => item.spaceId === spaceId).sort((a, b) => b.versionNumber - a.versionNumber), [spaceId, versions]); const selected = currentVersions.find((item) => item.id === selectedId) || currentVersions[0]; const previous = selected ? currentVersions.find((item) => item.versionNumber === selected.versionNumber - 1) : undefined;
  const state = parseSnapshot(selected?.snapshotJson); const before = parseSnapshot(previous?.snapshotJson); const diff = compareNodes(before.nodes, state.nodes); const sourceRecords = selected ? parseList(selected.sourceRecordIdsJson).map((id) => records.find((record) => record.id === id)).filter(Boolean) as RecordRef[] : [];
  async function restore() { if (!selected) return; setMessage("正在以这个历史快照创建新版本…"); const response = await fetch("/api/bases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "restore_version", versionId: selected.id }) }); if (response.ok) { await load(); setMessage("已恢复为一个新版本；原有历史没有被覆盖。"); } else setMessage("恢复失败，请稍后重试。"); }
  async function remove() { if (!selected) return; const response = await fetch("/api/bases", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ versionId: selected.id }) }); if (response.ok) { setSelectedId(""); await load(); setMessage("版本已删除，当前工作基座没有被改变。"); } }
  return <div className="version-ledger"><header className="version-hero"><div><span className="eyebrow">LIVING HISTORY · 可操作的体系演化史</span><h1 className="gothic-display-title">Living<br /><span>History</span></h1><p>查看任意版本的完整快照、变化依据和影响。恢复会生成新版本，不会抹掉中间历史。</p></div><div className="version-count"><strong>{versions.length}</strong><span>已发布版本</span></div></header>
    <div className="version-layout"><aside className="version-sidebar"><label>选择基座<select value={spaceId} onChange={(event) => { const next = event.target.value; setSpaceId(next); setSelectedId(versions.find((item) => item.spaceId === next)?.id || ""); }}>{spaces.map((space) => <option value={space.id} key={space.id}>{space.name}</option>)}</select></label><div>{currentVersions.map((version) => <button className={selected?.id === version.id ? "active" : ""} key={version.id} onClick={() => setSelectedId(version.id)}><i>v{version.versionNumber}</i><span><strong>{version.title}</strong><small>{new Date(version.createdAt).toLocaleString("zh-CN")}</small></span></button>)}</div>{!currentVersions.length && <p>这个基座还没有正式版本。请在体系全貌页发布当前工作基座。</p>}</aside>
      <main className="version-stage">{selected ? <><header><div><span className="eyebrow">VERSION {selected.versionNumber}</span><h2>{selected.title}</h2><p>{selected.summary}</p></div><div><button className="ghost-button" onClick={() => void restore()}>以此版本恢复</button><button className="quiet-action quiet-danger" onClick={() => void remove()}>删除版本</button></div></header><section className="version-diff-summary"><div><strong>＋ {diff.added.length}</strong><span>新增</span></div><div><strong>± {diff.changed.length}</strong><span>修改</span></div><div><strong>− {diff.removed.length}</strong><span>移除</span></div><div><strong>{state.nodes.length}</strong><span>完整节点</span></div></section>
        <section className="version-section"><h3>这个版本改变了什么</h3><div className="version-diff-list">{diff.added.map((node) => <article className="added" key={node.id}><span>新增</span><strong>{node.title}</strong><p>{node.content}</p></article>)}{diff.changed.map(({ after }) => <article className="changed" key={after.id}><span>修改</span><strong>{after.title}</strong><p>{after.content}</p></article>)}{diff.removed.map((node) => <article className="removed" key={node.id}><span>移除</span><strong>{node.title}</strong><p>{node.content}</p></article>)}{!previous && <article className="added"><span>初始快照</span><strong>这是该基座保存的第一个完整版本</strong><p>后续版本会在这里显示与上一版的真实差异。</p></article>}</div></section>
        <section className="version-section"><h3>由哪些思维记录促成</h3>{sourceRecords.length ? <div className="version-sources">{sourceRecords.map((record) => <article key={record.id}><span>↗</span><div><strong>{record.title}</strong><p>{record.source}</p></div></article>)}</div> : <p className="version-empty">这是一次手动发布，没有绑定特定记录。</p>}</section>
        <section className="version-section"><h3>完整基座快照</h3><div className="version-snapshot">{Object.entries(groupByType(state.nodes)).map(([type, nodes]) => <section key={type}><span>{type}</span>{nodes.map((node) => <article key={node.id}><strong>{node.title}</strong><p>{node.content}</p></article>)}</section>)}</div></section></> : <div className="version-empty-stage"><span>◷</span><h2>发布第一版，让基座开始拥有历史</h2><p>之后每次从思维记录接受融合补丁，也会自动形成新版本。</p></div>}{message && <div className="base-toast">{message}<button onClick={() => setMessage("")}>×</button></div>}</main></div>
  </div>;
}

function parseSnapshot(value?: string) { try { const raw = JSON.parse(value || "{}") as { space?: BaseSpace; nodes?: BaseNode[] }; return { space: raw.space, nodes: raw.nodes || [] }; } catch { return { space: undefined, nodes: [] as BaseNode[] }; } }
function parseList(value: string) { try { return JSON.parse(value || "[]") as string[]; } catch { return []; } }
function compareNodes(before: BaseNode[], after: BaseNode[]) { const old = new Map(before.map((node) => [node.id, node])); const next = new Map(after.map((node) => [node.id, node])); return { added: after.filter((node) => !old.has(node.id)), removed: before.filter((node) => !next.has(node.id)), changed: after.filter((node) => { const item = old.get(node.id); return item && (item.title !== node.title || item.content !== node.content || item.operationalJson !== node.operationalJson); }).map((node) => ({ before: old.get(node.id)!, after: node })) }; }
function groupByType(nodes: BaseNode[]) { return nodes.reduce<Record<string, BaseNode[]>>((groups, node) => { const key = node.nodeType; (groups[key] ||= []).push(node); return groups; }, {}); }
