"use client";

import { useEffect, useMemo, useState } from "react";

export type BaseSpace = { id: string; name: string; kind: string; description: string; scope: string; status: string; updatedAt: string };
export type BaseNode = { id: string; spaceId: string; parentId?: string | null; nodeType: string; title: string; content: string; operationalJson: string; sortOrder: number; updatedAt: string };
type BaseQuestion = { id: string; nodeId: string; question: string; rationale: string; trigger: string; completion: string; sortOrder: number };
type NodeLink = { id: string; fromNodeId: string; toNodeId: string; relation: string; label: string };
type SourceLink = { id: string; recordId: string; nodeId: string; relation: string; note: string };
type RecordRef = { id: string; title: string; source: string };
type PlaybookStep = { title: string; question: string; why: string; done: string };

const blankNode: BaseNode = { id: "", spaceId: "", parentId: "", nodeType: "method", title: "", content: "", operationalJson: "{}", sortOrder: 0, updatedAt: "" };
const blankQuestion = { id: "", nodeId: "", question: "", rationale: "", trigger: "", completion: "", sortOrder: 0 };
const relationNames: Record<string, string> = { supports: "支持", extends: "扩展", contrasts: "对照 / 冲突", precedes: "前置", example: "例证", related: "相关" };

export function CognitiveBasePage({ onOpenRecord }: { onOpenRecord?(id: string): void }) {
  const [spaces, setSpaces] = useState<BaseSpace[]>([]);
  const [nodes, setNodes] = useState<BaseNode[]>([]);
  const [questions, setQuestions] = useState<BaseQuestion[]>([]);
  const [nodeLinks, setNodeLinks] = useState<NodeLink[]>([]);
  const [sourceLinks, setSourceLinks] = useState<SourceLink[]>([]);
  const [records, setRecords] = useState<RecordRef[]>([]);
  const [spaceId, setSpaceId] = useState("meta-core");
  const [selectedNodeId, setSelectedNodeId] = useState("");
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const [editingNode, setEditingNode] = useState<BaseNode | null>(null);
  const [editingQuestion, setEditingQuestion] = useState<BaseQuestion | null>(null);
  const [editingSpace, setEditingSpace] = useState<BaseSpace | null>(null);
  const [overviewOpen, setOverviewOpen] = useState(false);
  const [overviewScale, setOverviewScale] = useState(1);
  const [createDomain, setCreateDomain] = useState(false);
  const [newDomain, setNewDomain] = useState({ name: "", description: "", scope: "" });
  const [linkTarget, setLinkTarget] = useState("");
  const [linkRelation, setLinkRelation] = useState("supports");
  const [sourceRecordId, setSourceRecordId] = useState("");
  const [sourceNote, setSourceNote] = useState("");
  const [message, setMessage] = useState("");

  async function load() {
    const response = await fetch("/api/bases"); const data = await response.json();
    if (!response.ok) throw new Error(data.error || "读取思维基座失败");
    setSpaces(data.spaces || []); setNodes(data.nodes || []); setQuestions(data.questions || []); setNodeLinks(data.nodeLinks || []); setSourceLinks(data.recordLinks || []); setRecords(data.records || []);
  }
  useEffect(() => { void load().catch((error) => setMessage(error.message)); }, []);

  const currentSpace = spaces.find((item) => item.id === spaceId) || spaces[0];
  const ownNodes = useMemo(() => nodes.filter((item) => item.spaceId === currentSpace?.id), [currentSpace?.id, nodes]);
  const modules = ownNodes.filter((node) => node.nodeType !== "playbook");
  const playbooks = ownNodes.filter((node) => node.nodeType === "playbook");
  const roots = modules.filter((node) => !node.parentId || !modules.some((parent) => parent.id === node.parentId));
  const selectedNode = nodes.find((item) => item.id === selectedNodeId) || roots[0] || playbooks[0];
  const selectedQuestions = questions.filter((item) => item.nodeId === selectedNode?.id);
  const linkedSources = selectedNode ? sourceLinks.filter((item) => item.nodeId === selectedNode.id).map((link) => ({ link, record: records.find((record) => record.id === link.recordId) })).filter((item) => item.record) : [];
  const related = selectedNode ? nodeLinks.filter((link) => link.fromNodeId === selectedNode.id || link.toNodeId === selectedNode.id).map((link) => ({ link, node: nodes.find((node) => node.id === (link.fromNodeId === selectedNode.id ? link.toNodeId : link.fromNodeId)) })).filter((item) => item.node) : [];

  async function post(body: unknown) { const response = await fetch("/api/bases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "操作失败"); return data; }
  async function saveNode() { if (!editingNode?.title.trim() || !currentSpace) return; let operational: unknown = {}; try { operational = JSON.parse(editingNode.operationalJson || "{}"); } catch { setMessage("流程步骤格式无效"); return; } await post({ action: editingNode.id ? "update_node" : "create_node", ...editingNode, spaceId: currentSpace.id, parentId: editingNode.parentId || null, nodeType: editingNode.nodeType === "playbook" ? "playbook" : "method", operational }); setEditingNode(null); await load(); setMessage("内容已保存，后续分析将读取这次修改。"); }
  async function deleteNode(id: string) { if (!confirm("删除该模组？子模组会保留并成为顶层模组。")) return; await post({ action: "delete_node", id }); setSelectedNodeId(""); await load(); }
  async function saveQuestion() { if (!editingQuestion?.question.trim() || !selectedNode) return; await post({ action: editingQuestion.id ? "update_question" : "create_question", ...editingQuestion, nodeId: selectedNode.id }); setEditingQuestion(null); await load(); setMessage("启发式问题已进入分析引擎。"); }
  async function deleteQuestion(id: string) { await post({ action: "delete_question", id }); await load(); }
  async function saveSpace() { if (!editingSpace) return; await post({ action: "update_space", ...editingSpace }); setEditingSpace(null); await load(); }
  async function addDomain() { if (!newDomain.name.trim()) return; const data = await post({ action: "create_space", kind: "domain", ...newDomain }); setCreateDomain(false); setNewDomain({ name: "", description: "", scope: "" }); await load(); setSpaceId(data.space.id); }
  async function publish() { if (!currentSpace) return; await post({ action: "publish", spaceId: currentSpace.id, title: `${currentSpace.name} · 手动发布`, summary: "认知树、启发式问题和执行流程的人工检点版本" }); setMessage("新版本已发布，历史快照保留了当前结构与问题。"); }
  async function addLink() { if (!selectedNode || !linkTarget) return; await post({ action: "create_link", fromNodeId: selectedNode.id, toNodeId: linkTarget, relation: linkRelation }); setLinkTarget(""); await load(); }
  async function addSource() { if (!selectedNode || !sourceRecordId) return; await post({ action: "create_record_link", recordId: sourceRecordId, nodeId: selectedNode.id, relation: "source", note: sourceNote || "手动确认为该模组来源" }); setSourceRecordId(""); setSourceNote(""); await load(); }
  function startNode(kind: "module" | "playbook", parentId = "") { setEditingNode({ ...blankNode, spaceId: currentSpace?.id || "", parentId, nodeType: kind === "playbook" ? "playbook" : "method", operationalJson: kind === "playbook" ? '{"steps":[]}' : "{}" }); }
  function steps(node: BaseNode) { try { return ((JSON.parse(node.operationalJson || "{}") as { steps?: PlaybookStep[] }).steps || []); } catch { return []; } }
  function stepsText(node: BaseNode) { return steps(node).map((item) => [item.title, item.question, item.why, item.done].join("｜")).join("\n"); }
  function updateSteps(value: string) { if (!editingNode) return; const next = value.split("\n").map((line) => { const [title, question, why, done] = line.split("｜"); return { title: title?.trim() || "步骤", question: question?.trim() || "", why: why?.trim() || "", done: done?.trim() || "" }; }).filter((item) => item.question); setEditingNode({ ...editingNode, operationalJson: JSON.stringify({ steps: next }) }); }
  function toggle(id: string) { setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }

  function TreeRow({ node, depth = 0 }: { node: BaseNode; depth?: number }) {
    const children = modules.filter((item) => item.parentId === node.id);
    const open = expanded.has(node.id) || depth < 1;
    return <div className="cognitive-tree-branch"><div className={`cognitive-tree-row ${selectedNode?.id === node.id ? "active" : ""}`} style={{ paddingLeft: 12 + depth * 18 }}><button className="tree-toggle" disabled={!children.length} onClick={() => toggle(node.id)}>{children.length ? (open ? "−" : "+") : "·"}</button><button className="tree-node-label" onClick={() => setSelectedNodeId(node.id)}><strong>{node.title}</strong><small>{questions.filter((item) => item.nodeId === node.id).length} 问</small></button><button className="tree-add-child" title="新增子模组" onClick={() => startNode("module", node.id)}>＋</button></div>{open && children.map((child) => <TreeRow key={child.id} node={child} depth={depth + 1} />)}</div>;
  }

  return <div className="base-workbench cognitive-os">
    <header className="base-hero"><div><span className="eyebrow">PERSONAL COGNITIVE OS · 体系全貌</span><h1 className="gothic-display-title">Cognitive<br /><span>Atlas</span></h1><p>左侧管理认知结构，右侧维护含义与启发式问题；分析、观照和报告都读取这里的当前版本。</p></div><div className="base-vitals"><div><strong>{modules.length}</strong><span>认知模组</span></div><div><strong>{questions.filter((item) => modules.some((node) => node.id === item.nodeId)).length}</strong><span>启发式问题</span></div><div><strong>{playbooks.length}</strong><span>可执行流程</span></div></div></header>
    <nav className="base-space-tabs"><div>{spaces.map((space) => <button className={currentSpace?.id === space.id ? "active" : ""} key={space.id} onClick={() => { setSpaceId(space.id); setSelectedNodeId(""); }}><i>{space.kind === "meta" ? "META" : "FIELD"}</i><strong>{space.name}</strong><small>{nodes.filter((node) => node.spaceId === space.id).length} 项</small></button>)}</div><button className="add-space-button" onClick={() => setCreateDomain(true)}>＋ 新增领域基座</button></nav>
    {currentSpace && <><section className="base-space-intro"><div><span>{currentSpace.kind === "meta" ? "元认知内核" : "领域化基座"}</span><h2>{currentSpace.name}</h2><p>{currentSpace.description}</p><small>适用范围：{currentSpace.scope}</small></div><div><button className="quiet-action" onClick={() => setOverviewOpen(true)}>◎ 一键查看全貌</button><button className="quiet-action" onClick={() => setEditingSpace({ ...currentSpace })}>编辑边界</button><button className="primary-button compact" onClick={() => void publish()}>发布新版本</button></div></section>
      <div className="base-canvas cognitive-tree-layout"><aside className="base-node-rail"><div className="base-rail-head"><span>认知结构</span><button onClick={() => startNode("module")}>＋</button></div><section className="cognitive-tree-list"><h3>认知模组<small>{modules.length}</small></h3>{roots.map((node) => <TreeRow key={node.id} node={node} />)}<button className="base-add-node" onClick={() => startNode("module")}>＋ 新建顶层模组</button></section><section className="playbook-rail"><h3>可执行流程<small>{playbooks.length}</small></h3>{playbooks.map((node) => <button key={node.id} className={selectedNode?.id === node.id ? "active" : ""} onClick={() => setSelectedNodeId(node.id)}><span>▶</span><strong>{node.title}</strong><i>{steps(node).length}</i></button>)}<button className="base-add-node" onClick={() => startNode("playbook")}>＋ 新建可执行流程</button></section></aside>
      <main className="base-node-stage">{selectedNode ? <><header><div><span>{selectedNode.nodeType === "playbook" ? "可执行流程" : "认知模组"}</span><h2>{selectedNode.title}</h2></div><div><button className="quiet-action" onClick={() => setEditingNode({ ...selectedNode })}>编辑</button><button className="quiet-action quiet-danger" onClick={() => void deleteNode(selectedNode.id)}>删除</button></div></header><article className="base-node-content"><p>{selectedNode.content || "还没有写下这个模组的含义、用途和边界。"}</p>{selectedNode.nodeType === "playbook" && <PlaybookPreview items={steps(selectedNode)} />}</article>
        {selectedNode.nodeType !== "playbook" && <section className="heuristic-question-section"><header><div><span className="eyebrow">HEURISTIC QUESTIONS</span><h3>这个模组怎样在思考时发问？</h3><p>这些问题会直接进入后续分析。问题不求多，只保留能触发具体认知动作的提问。</p></div><button className="primary-button compact" onClick={() => setEditingQuestion({ ...blankQuestion, nodeId: selectedNode.id })}>＋ 新增问题</button></header><div className="heuristic-question-list">{selectedQuestions.length ? selectedQuestions.map((item, index) => <article className="heuristic-question-card" key={item.id}><i>Q{index + 1}</i><div><h4>{item.question}</h4><p>{item.rationale || "尚未填写构建依据。"}</p><footer><span>触发：{item.trigger || "通用"}</span><span>完成：{item.completion || "未定义"}</span></footer></div><aside><button onClick={() => setEditingQuestion({ ...item })}>编辑</button><button onClick={() => void deleteQuestion(item.id)}>删除</button></aside></article>) : <div className="base-empty">还没有启发式问题。新增后，系统才能知道这个模组具体怎样被调用。</div>}</div></section>}
        <div className="base-links-grid"><section><h3>来自哪些思维记录</h3>{linkedSources.map(({ link, record }) => <article className="compact-source" key={link.id}><button onClick={() => record && onOpenRecord?.(record.id)}><strong>{record?.title}</strong><small>{link.note}</small></button><button onClick={async () => { await post({ action: "delete_record_link", id: link.id }); await load(); }}>×</button></article>)}<div className="base-source-compose"><select value={sourceRecordId} onChange={(event) => setSourceRecordId(event.target.value)}><option value="">选择思维记录</option>{records.filter((record) => !linkedSources.some((item) => item.record?.id === record.id)).map((record) => <option value={record.id} key={record.id}>{record.title}</option>)}</select><input value={sourceNote} onChange={(event) => setSourceNote(event.target.value)} placeholder="它为什么是来源（可选）" /><button disabled={!sourceRecordId} onClick={() => void addSource()}>添加</button></div></section><section><h3>与基座其他部分的关系</h3>{related.map(({ link, node }) => <div className="base-relation" key={link.id}><span>{relationNames[link.relation] || link.relation}</span><strong>{node?.title}</strong><button onClick={async () => { await post({ action: "delete_link", id: link.id }); await load(); }}>×</button></div>)}<div className="base-link-compose"><select value={linkRelation} onChange={(event) => setLinkRelation(event.target.value)}><option value="supports">支持</option><option value="extends">扩展</option><option value="contrasts">对照 / 冲突</option><option value="precedes">前置</option><option value="example">例证</option></select><select value={linkTarget} onChange={(event) => setLinkTarget(event.target.value)}><option value="">选择另一模组或流程</option>{nodes.filter((item) => item.id !== selectedNode.id).map((node) => <option value={node.id} key={node.id}>{node.title}</option>)}</select><button disabled={!linkTarget} onClick={() => void addLink()}>建立双向关系</button></div></section></div></> : <div className="base-empty-stage"><h2>从左侧选择一个认知模组</h2></div>}</main></div></>}
    {message && <div className="base-toast">{message}<button onClick={() => setMessage("")}>×</button></div>}
    {editingNode && <Editor title={`${editingNode.id ? "编辑" : "新建"}${editingNode.nodeType === "playbook" ? "可执行流程" : "认知模组"}`} onClose={() => setEditingNode(null)} onSave={() => void saveNode()}><label>上级模组<select value={editingNode.parentId || ""} disabled={editingNode.nodeType === "playbook"} onChange={(event) => setEditingNode({ ...editingNode, parentId: event.target.value })}><option value="">无上级模组</option>{modules.filter((node) => node.id !== editingNode.id).map((node) => <option value={node.id} key={node.id}>{node.title}</option>)}</select></label><label>名称<input value={editingNode.title} onChange={(event) => setEditingNode({ ...editingNode, title: event.target.value })} /></label><label>通俗说明<textarea value={editingNode.content} onChange={(event) => setEditingNode({ ...editingNode, content: event.target.value })} placeholder="它是什么、为什么重要、什么时候使用、边界在哪里？" /></label>{editingNode.nodeType === "playbook" && <label>连续步骤<small>每行：步骤名｜核心问题｜为什么问｜完成标准</small><textarea className="playbook-steps-editor" value={stepsText(editingNode)} onChange={(event) => updateSteps(event.target.value)} /></label>}</Editor>}
    {editingQuestion && <Editor title={editingQuestion.id ? "编辑启发式问题" : "新增启发式问题"} onClose={() => setEditingQuestion(null)} onSave={() => void saveQuestion()}><label>问题<input value={editingQuestion.question} onChange={(event) => setEditingQuestion({ ...editingQuestion, question: event.target.value })} placeholder="一个能触发具体思考动作的问题" /></label><label>构建依据<textarea value={editingQuestion.rationale} onChange={(event) => setEditingQuestion({ ...editingQuestion, rationale: event.target.value })} placeholder="为什么这样问？它帮助发现什么缺口？" /></label><label>何时触发<input value={editingQuestion.trigger} onChange={(event) => setEditingQuestion({ ...editingQuestion, trigger: event.target.value })} placeholder="例如：出现模糊概念时" /></label><label>怎样算完成<input value={editingQuestion.completion} onChange={(event) => setEditingQuestion({ ...editingQuestion, completion: event.target.value })} placeholder="例如：能给出定义、例子和反例" /></label></Editor>}
    {editingSpace && <Editor title="编辑基座使命与边界" onClose={() => setEditingSpace(null)} onSave={() => void saveSpace()}><label>名称<input value={editingSpace.name} onChange={(event) => setEditingSpace({ ...editingSpace, name: event.target.value })} /></label><label>它负责帮助我做什么<textarea value={editingSpace.description} onChange={(event) => setEditingSpace({ ...editingSpace, description: event.target.value })} /></label><label>适用范围<textarea value={editingSpace.scope} onChange={(event) => setEditingSpace({ ...editingSpace, scope: event.target.value })} /></label></Editor>}
    {createDomain && <Editor title="创建一个领域基座" onClose={() => setCreateDomain(false)} onSave={() => void addDomain()}><label>领域名称<input value={newDomain.name} onChange={(event) => setNewDomain({ ...newDomain, name: event.target.value })} /></label><label>它负责帮助我做什么<textarea value={newDomain.description} onChange={(event) => setNewDomain({ ...newDomain, description: event.target.value })} /></label><label>边界与适用场景<textarea value={newDomain.scope} onChange={(event) => setNewDomain({ ...newDomain, scope: event.target.value })} /></label></Editor>}
    {overviewOpen && <div className="cognitive-overview"><header><div><span className="eyebrow">SYSTEM ATLAS</span><h2>{currentSpace?.name} · 全貌</h2></div><div><button onClick={() => setOverviewScale((value) => Math.max(.65, value - .1))}>−</button><span>{Math.round(overviewScale * 100)}%</span><button onClick={() => setOverviewScale((value) => Math.min(1.5, value + .1))}>＋</button><button className="overview-close" onClick={() => setOverviewOpen(false)}>退出全貌</button></div></header><div className="overview-scroll"><div className="overview-board" style={{ transform: `scale(${overviewScale})` }}><section><h3>认知结构</h3><div className="overview-forest">{roots.map((node) => <OverviewNode key={node.id} node={node} nodes={modules} questions={questions} onSelect={(id) => { setSelectedNodeId(id); setOverviewOpen(false); }} />)}</div></section><section className="overview-flows"><h3>可执行流程</h3>{playbooks.map((flow) => <PlaybookPreview key={flow.id} items={steps(flow)} />)}</section></div></div></div>}
  </div>;
}

function Editor({ title, children, onClose, onSave }: { title: string; children: React.ReactNode; onClose(): void; onSave(): void }) { return <div className="modal-backdrop"><section className="card base-editor-modal"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">EDIT THE LIVING SYSTEM</span><h2>{title}</h2>{children}<footer><button className="ghost-button" onClick={onClose}>取消</button><button className="primary-button" onClick={onSave}>保存并用于后续分析</button></footer></section></div>; }
function PlaybookPreview({ items }: { items: PlaybookStep[] }) { return <section className="playbook-preview vertical"><header><div><span>可执行思维流程</span><strong>{items.length} 个连续步骤</strong></div></header><div>{items.map((step, index) => <article key={`${step.title}-${index}`}><i>{String(index + 1).padStart(2, "0")}</i><div><strong>{step.title}</strong><p>{step.question}</p><small><b>为什么问：</b>{step.why}</small><small><b>完成标准：</b>{step.done}</small></div></article>)}</div></section>; }
function OverviewNode({ node, nodes, questions, onSelect }: { node: BaseNode; nodes: BaseNode[]; questions: BaseQuestion[]; onSelect(id: string): void }) { const children = nodes.filter((item) => item.parentId === node.id); return <div className="overview-tree-node"><button onClick={() => onSelect(node.id)}><span>{node.title}</span><small>{node.content || "尚无说明"}</small><i>{questions.filter((item) => item.nodeId === node.id).length} 个问题</i></button>{children.length > 0 && <div className="overview-children">{children.map((child) => <OverviewNode key={child.id} node={child} nodes={nodes} questions={questions} onSelect={onSelect} />)}</div>}</div>; }
