"use client";

import { useEffect, useMemo, useState } from "react";

export type BaseSpace = { id: string; name: string; kind: string; description: string; scope: string; status: string; updatedAt: string };
export type BaseNode = { id: string; spaceId: string; parentId?: string | null; nodeType: string; title: string; content: string; operationalJson: string; sortOrder: number; updatedAt: string };
type NodeLink = { id: string; fromNodeId: string; toNodeId: string; relation: string; label: string };
type SourceLink = { id: string; recordId: string; nodeId: string; relation: string; note: string };
type RecordRef = { id: string; title: string; source: string };
type PlaybookStep = { title: string; question: string; why: string; done: string };

const blankNode = { id: "", spaceId: "", parentId: "", nodeType: "method", title: "", content: "", operationalJson: "{}", sortOrder: 0, updatedAt: "" };
const relationNames: Record<string, string> = { supports: "支持", extends: "扩展", contrasts: "对照 / 冲突", precedes: "前置步骤", example: "例证", related: "相关" };

export function CognitiveBasePage({ onOpenRecord }: { onOpenRecord?(id: string): void }) {
  const [spaces, setSpaces] = useState<BaseSpace[]>([]);
  const [nodes, setNodes] = useState<BaseNode[]>([]);
  const [nodeLinks, setNodeLinks] = useState<NodeLink[]>([]);
  const [sourceLinks, setSourceLinks] = useState<SourceLink[]>([]);
  const [records, setRecords] = useState<RecordRef[]>([]);
  const [spaceId, setSpaceId] = useState("meta-core");
  const [selectedNodeId, setSelectedNodeId] = useState("");
  const [editingNode, setEditingNode] = useState<BaseNode | null>(null);
  const [editingSpace, setEditingSpace] = useState<BaseSpace | null>(null);
  const [createDomain, setCreateDomain] = useState(false);
  const [newDomain, setNewDomain] = useState({ name: "", description: "", scope: "" });
  const [message, setMessage] = useState("");
  const [linkTarget, setLinkTarget] = useState("");
  const [linkRelation, setLinkRelation] = useState("supports");
  const [sourceRecordId, setSourceRecordId] = useState("");
  const [sourceNote, setSourceNote] = useState("");

  async function load() {
    const response = await fetch("/api/bases"); const data = await response.json();
    if (response.ok) { setSpaces(data.spaces || []); setNodes(data.nodes || []); setNodeLinks(data.nodeLinks || []); setSourceLinks(data.recordLinks || []); setRecords(data.records || []); if (!spaceId && data.spaces?.[0]) setSpaceId(data.spaces[0].id); }
  }
  useEffect(() => { fetch("/api/bases").then((response) => response.ok ? response.json() : null).then((data) => { if (!data) return; setSpaces(data.spaces || []); setNodes(data.nodes || []); setNodeLinks(data.nodeLinks || []); setSourceLinks(data.recordLinks || []); setRecords(data.records || []); if (data.spaces?.[0]) setSpaceId((current) => current || data.spaces[0].id); }).catch(() => undefined); }, []);

  const currentSpace = spaces.find((item) => item.id === spaceId) || spaces[0];
  const ownNodes = useMemo(() => nodes.filter((item) => item.spaceId === currentSpace?.id), [currentSpace?.id, nodes]);
  const cognitiveModules = ownNodes.filter((node) => node.nodeType !== "playbook");
  const playbooks = ownNodes.filter((node) => node.nodeType === "playbook");
  const selectedNode = nodes.find((item) => item.id === selectedNodeId) || cognitiveModules[0] || playbooks[0];
  const linkedSources = selectedNode ? sourceLinks.filter((item) => item.nodeId === selectedNode.id).map((link) => ({ link, record: records.find((record) => record.id === link.recordId) })).filter((item) => item.record) : [];
  const availableRecords = selectedNode ? records.filter((record) => !sourceLinks.some((link) => link.nodeId === selectedNode.id && link.recordId === record.id)) : [];
  const related = selectedNode ? nodeLinks.filter((link) => link.fromNodeId === selectedNode.id || link.toNodeId === selectedNode.id).map((link) => ({ link, node: nodes.find((node) => node.id === (link.fromNodeId === selectedNode.id ? link.toNodeId : link.fromNodeId)) })).filter((item) => item.node) : [];

  async function post(body: unknown) { const response = await fetch("/api/bases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "操作失败"); return data; }
  async function saveNode() { if (!editingNode?.title.trim() || !currentSpace) return; setMessage("正在保存…"); try { let operational: unknown = {}; try { operational = JSON.parse(editingNode.operationalJson || "{}"); } catch { throw new Error("流程步骤格式无效，请重新编辑步骤"); } await post({ action: editingNode.id ? "update_node" : "create_node", id: editingNode.id || undefined, spaceId: currentSpace.id, parentId: editingNode.parentId || null, nodeType: editingNode.nodeType === "playbook" ? "playbook" : "method", title: editingNode.title, content: editingNode.content, operational }); setEditingNode(null); await load(); setMessage(editingNode.nodeType === "playbook" ? "可执行流程已保存。" : "认知模组已保存。"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } }
  async function deleteNode(id: string) { await post({ action: "delete_node", id }); setSelectedNodeId(""); await load(); }
  async function saveSpace() { if (!editingSpace) return; await post({ action: "update_space", id: editingSpace.id, name: editingSpace.name, description: editingSpace.description, scope: editingSpace.scope }); setEditingSpace(null); await load(); }
  async function addDomain() { if (!newDomain.name.trim()) return; const data = await post({ action: "create_space", kind: "domain", ...newDomain }); setCreateDomain(false); setNewDomain({ name: "", description: "", scope: "" }); await load(); setSpaceId(data.space.id); }
  async function publish() { if (!currentSpace) return; setMessage("正在生成可追溯的新版本…"); await post({ action: "publish", spaceId: currentSpace.id, title: `${currentSpace.name} · 手动发布`, summary: "手动审阅并发布当前工作基座" }); setMessage("新版本已发布，之后的体系分析会读取当前内容。"); }
  async function addLink() { if (!selectedNode || !linkTarget) return; await post({ action: "create_link", fromNodeId: selectedNode.id, toNodeId: linkTarget, relation: linkRelation, label: `${selectedNode.title} ↔ ${nodes.find((item) => item.id === linkTarget)?.title || "关联节点"}` }); setLinkTarget(""); await load(); }
  async function deleteLink(id: string) { await post({ action: "delete_link", id }); await load(); }
  async function addSource() { if (!selectedNode || !sourceRecordId) return; await post({ action: "create_record_link", recordId: sourceRecordId, nodeId: selectedNode.id, relation: "source", note: sourceNote.trim() || "手动确认为该认知模组的来源" }); setSourceRecordId(""); setSourceNote(""); await load(); }
  async function deleteSource(id: string) { await post({ action: "delete_record_link", id }); await load(); }

  function updateSteps(value: string) { if (!editingNode) return; const steps = value.split("\n").map((line) => { const [title, question, why, done] = line.split("｜"); return { title: title?.trim() || "步骤", question: question?.trim() || "", why: why?.trim() || "", done: done?.trim() || "" }; }).filter((step) => step.question); setEditingNode({ ...editingNode, operationalJson: JSON.stringify({ steps }) }); }
  function stepsText(node: BaseNode) { try { const parsed = JSON.parse(node.operationalJson || "{}") as { steps?: PlaybookStep[] }; return (parsed.steps || []).map((step) => [step.title, step.question, step.why, step.done].join("｜")).join("\n"); } catch { return ""; } }
  function startNode(kind: "module" | "playbook") { setEditingNode({ ...blankNode, spaceId: currentSpace?.id || "", nodeType: kind === "playbook" ? "playbook" : "method", operationalJson: kind === "playbook" ? JSON.stringify({ steps: [] }) : "{}" }); }

  return <div className="base-workbench">
    <header className="base-hero"><div><span className="eyebrow">PERSONAL COGNITIVE OS · 当前正式思维体系</span><h1>不是收藏知识，<br />而是改变你怎样思考。</h1><p>认知模组保存你逐渐内化的认识；可执行流程把这些认识排成实际可用的思考顺序。</p></div><div className="base-vitals"><div><strong>{spaces.length}</strong><span>基座空间</span></div><div><strong>{nodes.length}</strong><span>认知模组与流程</span></div><div><strong>{sourceLinks.length}</strong><span>记录链接</span></div></div></header>
    <nav className="base-space-tabs"><div>{spaces.map((space) => <button className={currentSpace?.id === space.id ? "active" : ""} key={space.id} onClick={() => { setSpaceId(space.id); setSelectedNodeId(""); }}><i>{space.kind === "meta" ? "META" : "FIELD"}</i><strong>{space.name}</strong><small>{nodes.filter((node) => node.spaceId === space.id).length} 项内容</small></button>)}</div><button className="add-space-button" onClick={() => setCreateDomain(true)}>＋ 新增领域基座</button></nav>
    {currentSpace && <><section className="base-space-intro"><div><span>{currentSpace.kind === "meta" ? "元认知内核" : "领域化基座"}</span><h2>{currentSpace.name}</h2><p>{currentSpace.description || "还没有写下这个基座的使命。"}</p><small>适用范围：{currentSpace.scope || "尚未界定"}</small></div><div><button className="quiet-action" onClick={() => setEditingSpace({ ...currentSpace })}>✎ 编辑边界</button><button className="primary-button compact" onClick={() => void publish()}>发布为新版本</button></div></section>
      <div className="base-canvas">
        <aside className="base-node-rail"><div className="base-rail-head"><span>认知结构</span><button aria-label="新建认知模组" onClick={() => startNode("module")}>＋</button></div><section><h3>认知模组<small>{cognitiveModules.length}</small></h3>{cognitiveModules.map((node) => <button key={node.id} className={selectedNode?.id === node.id ? "active" : ""} onClick={() => setSelectedNodeId(node.id)}><span>·</span><strong>{node.title}</strong><i>{sourceLinks.filter((link) => link.nodeId === node.id).length}</i></button>)}<button className="base-add-node" onClick={() => startNode("module")}>＋ 新建认知模组</button></section><section className="playbook-rail"><h3>可执行流程<small>{playbooks.length}</small></h3>{playbooks.map((node) => <button key={node.id} className={selectedNode?.id === node.id ? "active" : ""} onClick={() => setSelectedNodeId(node.id)}><span>▶</span><strong>{node.title}</strong><i>{stepsText(node).split("\n").filter(Boolean).length}</i></button>)}<button className="base-add-node" onClick={() => startNode("playbook")}>＋ 新建可执行流程</button></section></aside>
        <main className="base-node-stage">{selectedNode ? <><header><div><span>{selectedNode.nodeType === "playbook" ? "可执行流程" : "认知模组"}</span><h2>{selectedNode.title}</h2></div><div><button className="quiet-action" onClick={() => setEditingNode({ ...selectedNode })}>✎ 编辑</button><button className="quiet-action quiet-danger" onClick={() => void deleteNode(selectedNode.id)}>⌫ 删除</button></div></header><article className="base-node-content"><p>{selectedNode.content || (selectedNode.nodeType === "playbook" ? "这个流程还没有说明。" : "这个认知模组还没有说明。")}</p>{selectedNode.nodeType === "playbook" && <PlaybookPreview node={selectedNode} />}</article><div className="base-links-grid"><section><h3>来自哪些思维记录</h3><div className="base-source-list">{linkedSources.length ? linkedSources.map(({ link, record }) => <article key={link.id}><button onClick={() => record && onOpenRecord?.(record.id)}><span>↗</span><div><strong>{record?.title}</strong><small>{record?.source}</small><p>{link.note}</p></div></button><button className="base-remove-link" aria-label={`删除来源 ${record?.title}`} onClick={() => void deleteSource(link.id)}>×</button></article>) : <p className="base-empty">尚无来源链接。你可以从已有记录中主动添加。</p>}</div><div className="base-source-compose"><select value={sourceRecordId} onChange={(event) => setSourceRecordId(event.target.value)}><option value="">选择一条思维记录</option>{availableRecords.map((record) => <option value={record.id} key={record.id}>{record.title}</option>)}</select><input value={sourceNote} onChange={(event) => setSourceNote(event.target.value)} placeholder="为什么它是这个模组的来源（可选）" /><button disabled={!sourceRecordId} onClick={() => void addSource()}>添加来源</button></div></section><section><h3>与基座其他部分的关系</h3>{related.length ? related.map(({ link, node }) => <div className="base-relation" key={link.id}><span>{relationNames[link.relation] || link.relation}</span><strong>{node?.title}</strong><button aria-label={`删除与 ${node?.title} 的关系`} onClick={() => void deleteLink(link.id)}>×</button></div>) : <p className="base-empty">尚未建立关系。</p>}<div className="base-link-compose"><select value={linkRelation} onChange={(event) => setLinkRelation(event.target.value)}><option value="supports">支持</option><option value="extends">扩展</option><option value="contrasts">对照 / 冲突</option><option value="precedes">前置步骤</option><option value="example">例证</option></select><select value={linkTarget} onChange={(event) => setLinkTarget(event.target.value)}><option value="">选择另一个模组或流程</option>{nodes.filter((item) => item.id !== selectedNode.id).map((node) => <option value={node.id} key={node.id}>{spaces.find((space) => space.id === node.spaceId)?.name} · {node.title}</option>)}</select><button disabled={!linkTarget} onClick={() => void addLink()}>建立双向关系</button></div></section></div></> : <div className="base-empty-stage"><span>∞</span><h2>选择一个认知模组或流程</h2><p>查看内容、来源与关联。</p></div>}</main>
      </div></>}
    {message && <div className="base-toast">{message}<button onClick={() => setMessage("")}>×</button></div>}
    {editingNode && <div className="modal-backdrop"><section className="card base-editor-modal"><button className="modal-close" onClick={() => setEditingNode(null)}>×</button><span className="eyebrow">{editingNode.nodeType === "playbook" ? "EDIT EXECUTABLE FLOW" : "EDIT COGNITIVE MODULE"}</span><h2>{editingNode.id ? "编辑" : "新建"}{editingNode.nodeType === "playbook" ? "可执行流程" : "认知模组"}</h2><label>上级模组<select value={editingNode.parentId || ""} onChange={(event) => setEditingNode({ ...editingNode, parentId: event.target.value })}><option value="">无上级模组</option>{ownNodes.filter((node) => node.id !== editingNode.id && node.nodeType !== "playbook").map((node) => <option value={node.id} key={node.id}>{node.title}</option>)}</select></label><label>名称<input value={editingNode.title} onChange={(event) => setEditingNode({ ...editingNode, title: event.target.value })} placeholder={editingNode.nodeType === "playbook" ? "这套流程叫什么？" : "这个认知模组叫什么？"} /></label><label>通俗说明<textarea value={editingNode.content} onChange={(event) => setEditingNode({ ...editingNode, content: event.target.value })} placeholder="它是什么、为什么重要、什么时候使用？" /></label>{editingNode.nodeType === "playbook" && <label>连续步骤 <small>每行：步骤名｜要问的问题｜为什么问｜完成标准</small><textarea className="playbook-steps-editor" value={stepsText(editingNode)} onChange={(event) => updateSteps(event.target.value)} placeholder="明确问题｜我究竟要解决什么？｜不同问题需要不同证据｜能用一句话说明问题" /></label>}<footer><button className="ghost-button" onClick={() => setEditingNode(null)}>取消</button><button className="primary-button" onClick={() => void saveNode()}>保存</button></footer></section></div>}
    {editingSpace && <div className="modal-backdrop"><section className="card base-editor-modal"><button className="modal-close" onClick={() => setEditingSpace(null)}>×</button><span className="eyebrow">DEFINE THE BOUNDARY</span><h2>编辑基座使命与边界</h2><label>名称<input value={editingSpace.name} onChange={(event) => setEditingSpace({ ...editingSpace, name: event.target.value })} /></label><label>它负责帮助我做什么<textarea value={editingSpace.description} onChange={(event) => setEditingSpace({ ...editingSpace, description: event.target.value })} /></label><label>适用范围<textarea value={editingSpace.scope} onChange={(event) => setEditingSpace({ ...editingSpace, scope: event.target.value })} /></label><footer><button className="ghost-button" onClick={() => setEditingSpace(null)}>取消</button><button className="primary-button" onClick={() => void saveSpace()}>保存边界</button></footer></section></div>}
    {createDomain && <div className="modal-backdrop"><section className="card base-editor-modal"><button className="modal-close" onClick={() => setCreateDomain(false)}>×</button><span className="eyebrow">NEW FIELD BASE</span><h2>创建一个领域基座</h2><p>它是一套“在这个领域里怎样理解、判断和行动”的方法。</p><label>领域名称<input value={newDomain.name} onChange={(event) => setNewDomain({ ...newDomain, name: event.target.value })} placeholder="例如：社会科学研究" /></label><label>它要帮助我做什么<textarea value={newDomain.description} onChange={(event) => setNewDomain({ ...newDomain, description: event.target.value })} /></label><label>边界与适用场景<textarea value={newDomain.scope} onChange={(event) => setNewDomain({ ...newDomain, scope: event.target.value })} /></label><footer><button className="ghost-button" onClick={() => setCreateDomain(false)}>取消</button><button className="primary-button" onClick={() => void addDomain()}>创建领域基座</button></footer></section></div>}
  </div>;
}

function PlaybookPreview({ node }: { node: BaseNode }) {
  let steps: PlaybookStep[] = []; try { steps = (JSON.parse(node.operationalJson || "{}") as { steps?: PlaybookStep[] }).steps || []; } catch { steps = []; }
  return <section className="playbook-preview vertical"><header><div><span>可执行思维流程</span><strong>{steps.length} 个连续步骤</strong></div></header><div>{steps.map((step, index) => <article key={`${step.title}-${index}`}><i>{String(index + 1).padStart(2, "0")}</i><div><strong>{step.title}</strong><p>{step.question}</p><small><b>为什么问：</b>{step.why}</small><small><b>完成标准：</b>{step.done}</small></div></article>)}</div>{!steps.length && <p className="base-empty">还没有步骤。点击“编辑”后逐行添加。</p>}</section>;
}
