"use client";

import { useEffect, useMemo, useState } from "react";

export type BaseSpace = { id: string; name: string; kind: string; description: string; scope: string; status: string; updatedAt: string };
export type BaseNode = { id: string; spaceId: string; parentId?: string | null; nodeType: string; title: string; content: string; operationalJson: string; sortOrder: number; updatedAt: string };
type NodeLink = { id: string; fromNodeId: string; toNodeId: string; relation: string; label: string };
type SourceLink = { id: string; recordId: string; nodeId: string; relation: string; note: string };
type RecordRef = { id: string; title: string; source: string };
type PlaybookStep = { title: string; question: string; why: string; done: string };

const nodeKinds: Record<string, string> = { principle: "原则", method: "方法", concept: "概念", viewpoint: "观点", evidence: "证据规则", example: "案例 / 反例", question: "开放问题", value: "价值立场", playbook: "可执行流程" };
const blankNode = { id: "", spaceId: "", parentId: "", nodeType: "method", title: "", content: "", operationalJson: "{}", sortOrder: 0, updatedAt: "" };

export function CognitiveBasePage({ onOpenRecord }: { onOpenRecord?(id: string): void }) {
  const [spaces, setSpaces] = useState<BaseSpace[]>([]); const [nodes, setNodes] = useState<BaseNode[]>([]); const [nodeLinks, setNodeLinks] = useState<NodeLink[]>([]); const [sourceLinks, setSourceLinks] = useState<SourceLink[]>([]); const [records, setRecords] = useState<RecordRef[]>([]);
  const [spaceId, setSpaceId] = useState("meta-core"); const [selectedNodeId, setSelectedNodeId] = useState(""); const [editingNode, setEditingNode] = useState<BaseNode | null>(null); const [editingSpace, setEditingSpace] = useState<BaseSpace | null>(null); const [createDomain, setCreateDomain] = useState(false); const [newDomain, setNewDomain] = useState({ name: "", description: "", scope: "" }); const [message, setMessage] = useState("");
  const [linkTarget, setLinkTarget] = useState(""); const [linkRelation, setLinkRelation] = useState("supports"); const [runner, setRunner] = useState<{ node: BaseNode; steps: PlaybookStep[]; index: number; answers: string[] } | null>(null); const [runnerText, setRunnerText] = useState(""); const [runnerAnswer, setRunnerAnswer] = useState("");

  async function load() { const response = await fetch("/api/bases"); const data = await response.json(); if (response.ok) { setSpaces(data.spaces || []); setNodes(data.nodes || []); setNodeLinks(data.nodeLinks || []); setSourceLinks(data.recordLinks || []); setRecords(data.records || []); if (!spaceId && data.spaces?.[0]) setSpaceId(data.spaces[0].id); } }
  useEffect(() => { fetch("/api/bases").then((response) => response.ok ? response.json() : null).then((data) => { if (!data) return; setSpaces(data.spaces || []); setNodes(data.nodes || []); setNodeLinks(data.nodeLinks || []); setSourceLinks(data.recordLinks || []); setRecords(data.records || []); if (data.spaces?.[0]) setSpaceId((current) => current || data.spaces[0].id); }).catch(() => undefined); }, []);
  const currentSpace = spaces.find((item) => item.id === spaceId) || spaces[0]; const ownNodes = useMemo(() => nodes.filter((item) => item.spaceId === currentSpace?.id), [currentSpace?.id, nodes]); const selectedNode = nodes.find((item) => item.id === selectedNodeId) || ownNodes[0];
  const linkedSources = selectedNode ? sourceLinks.filter((item) => item.nodeId === selectedNode.id).map((link) => ({ link, record: records.find((record) => record.id === link.recordId) })).filter((item) => item.record) : [];
  const related = selectedNode ? nodeLinks.filter((link) => link.fromNodeId === selectedNode.id || link.toNodeId === selectedNode.id).map((link) => ({ link, node: nodes.find((node) => node.id === (link.fromNodeId === selectedNode.id ? link.toNodeId : link.fromNodeId)) })).filter((item) => item.node) : [];

  async function post(body: unknown) { const response = await fetch("/api/bases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "操作失败"); return data; }
  async function saveNode() { if (!editingNode?.title.trim() || !currentSpace) return; setMessage("正在保存认知单元…"); try { let operational: unknown = {}; try { operational = JSON.parse(editingNode.operationalJson || "{}"); } catch { throw new Error("流程步骤格式无效，请重新编辑步骤"); } await post({ action: editingNode.id ? "update_node" : "create_node", id: editingNode.id || undefined, spaceId: currentSpace.id, parentId: editingNode.parentId || null, nodeType: editingNode.nodeType, title: editingNode.title, content: editingNode.content, operational }); setEditingNode(null); await load(); setMessage("已保存。发布新版本前，它属于当前工作基座。"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } }
  async function deleteNode(id: string) { await post({ action: "delete_node", id }); setSelectedNodeId(""); await load(); }
  async function saveSpace() { if (!editingSpace) return; await post({ action: "update_space", id: editingSpace.id, name: editingSpace.name, description: editingSpace.description, scope: editingSpace.scope }); setEditingSpace(null); await load(); }
  async function addDomain() { if (!newDomain.name.trim()) return; const data = await post({ action: "create_space", kind: "domain", ...newDomain }); setCreateDomain(false); setNewDomain({ name: "", description: "", scope: "" }); await load(); setSpaceId(data.space.id); }
  async function publish() { if (!currentSpace) return; setMessage("正在生成可追溯的新版本…"); await post({ action: "publish", spaceId: currentSpace.id, title: `${currentSpace.name} · 手动发布`, summary: "手动审阅并发布当前工作基座" }); setMessage("新版本已发布。之后的体系分析会读取当前基座内容。"); }
  async function addLink() { if (!selectedNode || !linkTarget) return; await post({ action: "create_link", fromNodeId: selectedNode.id, toNodeId: linkTarget, relation: linkRelation, label: `${selectedNode.title} ↔ ${nodes.find((item) => item.id === linkTarget)?.title || "关联节点"}` }); setLinkTarget(""); await load(); }

  function openRunner(node: BaseNode) { try { const parsed = JSON.parse(node.operationalJson || "{}") as { steps?: PlaybookStep[] }; setRunner({ node, steps: parsed.steps || [], index: 0, answers: [] }); setRunnerText(""); setRunnerAnswer(""); } catch { setMessage("这个流程还没有可执行步骤。"); } }
  function updateSteps(value: string) { if (!editingNode) return; const steps = value.split("\n").map((line) => { const [title, question, why, done] = line.split("｜"); return { title: title?.trim() || "步骤", question: question?.trim() || "", why: why?.trim() || "", done: done?.trim() || "" }; }).filter((step) => step.question); setEditingNode({ ...editingNode, operationalJson: JSON.stringify({ steps }) }); }
  function stepsText(node: BaseNode) { try { const parsed = JSON.parse(node.operationalJson || "{}") as { steps?: PlaybookStep[] }; return (parsed.steps || []).map((step) => [step.title, step.question, step.why, step.done].join("｜")).join("\n"); } catch { return ""; } }

  return <div className="base-workbench">
    <header className="base-hero"><div><span className="eyebrow">PERSONAL COGNITIVE OS · 当前正式思维体系</span><h1>不是收藏知识，<br />而是改变你怎样思考。</h1><p>万象基座负责“怎样思考”；领域基座负责“在某个领域怎样判断”。每个节点都可以编辑、追溯和实际执行。</p></div><div className="base-vitals"><div><strong>{spaces.length}</strong><span>基座空间</span></div><div><strong>{nodes.length}</strong><span>认知单元</span></div><div><strong>{sourceLinks.length}</strong><span>记录链接</span></div></div></header>
    <nav className="base-space-tabs"><div>{spaces.map((space) => <button className={currentSpace?.id === space.id ? "active" : ""} key={space.id} onClick={() => { setSpaceId(space.id); setSelectedNodeId(""); }}><i>{space.kind === "meta" ? "META" : "FIELD"}</i><strong>{space.name}</strong><small>{nodes.filter((node) => node.spaceId === space.id).length} 个单元</small></button>)}</div><button className="add-space-button" onClick={() => setCreateDomain(true)}>＋ 新增领域基座</button></nav>
    {currentSpace && <><section className="base-space-intro"><div><span>{currentSpace.kind === "meta" ? "元认知内核" : "领域化基座"}</span><h2>{currentSpace.name}</h2><p>{currentSpace.description || "还没有写下这个基座的使命。"}</p><small>适用范围：{currentSpace.scope || "尚未界定"}</small></div><div><button className="quiet-action" onClick={() => setEditingSpace({ ...currentSpace })}>✎ 编辑边界</button><button className="primary-button compact" onClick={() => void publish()}>发布为新版本</button></div></section>
      <div className="base-canvas">
        <aside className="base-node-rail"><div className="base-rail-head"><span>认知结构</span><button onClick={() => setEditingNode({ ...blankNode, spaceId: currentSpace.id })}>＋</button></div>{Object.entries(nodeKinds).map(([kind, label]) => { const group = ownNodes.filter((node) => node.nodeType === kind); if (!group.length) return null; return <section key={kind}><h3>{label}<small>{group.length}</small></h3>{group.map((node) => <button key={node.id} className={selectedNode?.id === node.id ? "active" : ""} onClick={() => setSelectedNodeId(node.id)}><span>{node.nodeType === "playbook" ? "▶" : "·"}</span><strong>{node.title}</strong><i>{sourceLinks.filter((link) => link.nodeId === node.id).length}</i></button>)}</section>; })}<button className="base-add-node" onClick={() => setEditingNode({ ...blankNode, spaceId: currentSpace.id })}>＋ 新建认知单元</button></aside>
        <main className="base-node-stage">{selectedNode ? <><header><div><span>{nodeKinds[selectedNode.nodeType] || selectedNode.nodeType}</span><h2>{selectedNode.title}</h2></div><div><button className="quiet-action" onClick={() => setEditingNode({ ...selectedNode })}>✎ 编辑</button><button className="quiet-action quiet-danger" onClick={() => void deleteNode(selectedNode.id)}>⌫ 删除</button></div></header><article className="base-node-content"><p>{selectedNode.content || "这个认知单元还没有说明。"}</p>{selectedNode.nodeType === "playbook" && <PlaybookPreview node={selectedNode} onRun={() => openRunner(selectedNode)} />}</article><div className="base-links-grid"><section><h3>来自哪些思维记录</h3>{linkedSources.length ? linkedSources.map(({ link, record }) => <button key={link.id} onClick={() => record && onOpenRecord?.(record.id)}><span>↗</span><div><strong>{record?.title}</strong><small>{record?.source}</small><p>{link.note}</p></div></button>) : <p className="base-empty">尚无来源链接。通过“融合工作台”加入记录后，会在这里形成双向链接。</p>}</section><section><h3>与基座其他部分的关系</h3>{related.map(({ link, node }) => <div className="base-relation" key={link.id}><span>{link.relation}</span><strong>{node?.title}</strong></div>)}<div className="base-link-compose"><select value={linkRelation} onChange={(event) => setLinkRelation(event.target.value)}><option value="supports">支持</option><option value="extends">扩展</option><option value="contrasts">对照 / 冲突</option><option value="precedes">前置步骤</option><option value="example">例证</option></select><select value={linkTarget} onChange={(event) => setLinkTarget(event.target.value)}><option value="">选择另一个节点</option>{nodes.filter((item) => item.id !== selectedNode.id).map((node) => <option value={node.id} key={node.id}>{spaces.find((space) => space.id === node.spaceId)?.name} · {node.title}</option>)}</select><button disabled={!linkTarget} onClick={() => void addLink()}>建立双向关系</button></div></section></div></> : <div className="base-empty-stage"><span>∞</span><h2>选择一个认知单元</h2><p>查看它的内容、来源、关联和可执行流程。</p></div>}</main>
      </div></>}
    {message && <div className="base-toast">{message}<button onClick={() => setMessage("")}>×</button></div>}
    {editingNode && <div className="modal-backdrop"><section className="card base-editor-modal"><button className="modal-close" onClick={() => setEditingNode(null)}>×</button><span className="eyebrow">EDIT COGNITIVE UNIT</span><h2>{editingNode.id ? "编辑认知单元" : "新建认知单元"}</h2><div className="base-editor-grid"><label>类型<select value={editingNode.nodeType} onChange={(event) => setEditingNode({ ...editingNode, nodeType: event.target.value })}>{Object.entries(nodeKinds).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>上级节点<select value={editingNode.parentId || ""} onChange={(event) => setEditingNode({ ...editingNode, parentId: event.target.value })}><option value="">无上级节点</option>{ownNodes.filter((node) => node.id !== editingNode.id).map((node) => <option value={node.id} key={node.id}>{node.title}</option>)}</select></label></div><label>名称<input value={editingNode.title} onChange={(event) => setEditingNode({ ...editingNode, title: event.target.value })} placeholder="这个认知单元叫什么？" /></label><label>通俗说明<textarea value={editingNode.content} onChange={(event) => setEditingNode({ ...editingNode, content: event.target.value })} placeholder="它是什么、为什么重要、什么时候使用？" /></label>{editingNode.nodeType === "playbook" && <label>可执行步骤 <small>每行：步骤名｜要问的问题｜为什么问｜完成标准</small><textarea className="playbook-steps-editor" value={stepsText(editingNode)} onChange={(event) => updateSteps(event.target.value)} placeholder="明确问题｜我究竟要解决什么？｜不同问题需要不同证据｜能用一句话说明问题" /></label>}<footer><button className="ghost-button" onClick={() => setEditingNode(null)}>取消</button><button className="primary-button" onClick={() => void saveNode()}>保存到工作基座</button></footer></section></div>}
    {editingSpace && <div className="modal-backdrop"><section className="card base-editor-modal"><button className="modal-close" onClick={() => setEditingSpace(null)}>×</button><span className="eyebrow">DEFINE THE BOUNDARY</span><h2>编辑基座使命与边界</h2><label>名称<input value={editingSpace.name} onChange={(event) => setEditingSpace({ ...editingSpace, name: event.target.value })} /></label><label>它负责帮助我做什么<textarea value={editingSpace.description} onChange={(event) => setEditingSpace({ ...editingSpace, description: event.target.value })} /></label><label>适用范围<textarea value={editingSpace.scope} onChange={(event) => setEditingSpace({ ...editingSpace, scope: event.target.value })} /></label><footer><button className="ghost-button" onClick={() => setEditingSpace(null)}>取消</button><button className="primary-button" onClick={() => void saveSpace()}>保存边界</button></footer></section></div>}
    {createDomain && <div className="modal-backdrop"><section className="card base-editor-modal"><button className="modal-close" onClick={() => setCreateDomain(false)}>×</button><span className="eyebrow">NEW FIELD BASE</span><h2>创建一个领域基座</h2><p>它不是文件夹，而是一套“在这个领域里怎样理解、判断和行动”的方法。</p><label>领域名称<input value={newDomain.name} onChange={(event) => setNewDomain({ ...newDomain, name: event.target.value })} placeholder="例如：社会科学研究" /></label><label>它要帮助我做什么<textarea value={newDomain.description} onChange={(event) => setNewDomain({ ...newDomain, description: event.target.value })} /></label><label>边界与适用场景<textarea value={newDomain.scope} onChange={(event) => setNewDomain({ ...newDomain, scope: event.target.value })} /></label><footer><button className="ghost-button" onClick={() => setCreateDomain(false)}>取消</button><button className="primary-button" onClick={() => void addDomain()}>创建领域基座</button></footer></section></div>}
    {runner && <div className="modal-backdrop"><section className="card playbook-runner"><button className="modal-close" onClick={() => setRunner(null)}>×</button><span className="eyebrow">GUIDED THINKING · 扶持模式</span><h2>{runner.node.title}</h2>{runner.index === 0 && runner.answers.length === 0 && <label className="runner-material">把要分析的问题或文本放在这里<textarea value={runnerText} onChange={(event) => setRunnerText(event.target.value)} /></label>}{runner.steps[runner.index] ? <><div className="runner-progress"><span style={{ width: `${((runner.index + 1) / Math.max(1, runner.steps.length)) * 100}%` }} /></div><article><small>第 {runner.index + 1} / {runner.steps.length} 步</small><h3>{runner.steps[runner.index].title}</h3><strong>{runner.steps[runner.index].question}</strong><p><b>为什么现在问：</b>{runner.steps[runner.index].why}</p><p><b>做到什么算完成：</b>{runner.steps[runner.index].done}</p></article><textarea value={runnerAnswer} onChange={(event) => setRunnerAnswer(event.target.value)} placeholder="先写下自己的回答；不知道时也可以写下卡住的地方。" /><footer><button className="ghost-button" onClick={() => setRunner({ ...runner, index: Math.max(0, runner.index - 1) })}>上一步</button><button className="primary-button" disabled={!runnerAnswer.trim()} onClick={() => { const answers = [...runner.answers, runnerAnswer]; if (runner.index + 1 >= runner.steps.length) setRunner({ ...runner, answers, index: runner.steps.length }); else setRunner({ ...runner, answers, index: runner.index + 1 }); setRunnerAnswer(""); }}>保存回答，继续 →</button></footer></> : <div className="runner-complete"><span>✓</span><h3>你已经走完这套思维流程</h3><p>重点不是得到唯一答案，而是让每一步都可见、可检查、可修改。</p><div>{runner.answers.map((answer, index) => <article key={index}><strong>{runner.steps[index]?.title}</strong><p>{answer}</p></article>)}</div><button className="primary-button" onClick={() => setRunner(null)}>完成本次练习</button></div>}</section></div>}
  </div>;
}

function PlaybookPreview({ node, onRun }: { node: BaseNode; onRun(): void }) { let steps: PlaybookStep[] = []; try { steps = (JSON.parse(node.operationalJson || "{}") as { steps?: PlaybookStep[] }).steps || []; } catch { steps = []; } return <section className="playbook-preview"><header><div><span>可执行思维程序</span><strong>{steps.length} 个连续步骤</strong></div><button onClick={onRun}>开始实践这套流程 →</button></header><div>{steps.map((step, index) => <article key={`${step.title}-${index}`}><i>{String(index + 1).padStart(2, "0")}</i><div><strong>{step.title}</strong><p>{step.question}</p><small>{step.why}</small></div></article>)}</div></section>; }
