"use client";

import { useEffect, useMemo, useState } from "react";
import type { BaseNode, BaseSpace } from "./CognitiveBasePage";

type RecordInput = { id: string; title: string; content: string; source: string; note: string; reportContent: string };
type PatchItem = { id: string; accepted: boolean; targetSpaceId: string; targetNodeId: string; action: "add" | "update" | "merge" | "link"; nodeType: string; title: string; currentContent: string; proposedContent: string; why: string; sourceEvidence: string; playbookStep: string };
type Proposal = { destination: string; synthesis: string; why: string; extractions: string[]; conflicts: string[]; impact: string[]; patches: PatchItem[] };

export function IntegrationStudio({ record, onBack, onApplied }: { record: RecordInput; onBack(): void; onApplied(): void }) {
  const [spaces, setSpaces] = useState<BaseSpace[]>([]); const [nodes, setNodes] = useState<BaseNode[]>([]); const [proposal, setProposal] = useState<Proposal | null>(null); const [proposalId, setProposalId] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [view, setView] = useState<"patches" | "mirror" | "impact">("patches");
  useEffect(() => { void Promise.all([fetch("/api/bases").then((r) => r.json()), fetch(`/api/integrations?recordId=${encodeURIComponent(record.id)}`).then((r) => r.json())]).then(([baseData, integrationData]) => { setSpaces(baseData.spaces || []); setNodes(baseData.nodes || []); const saved = integrationData.proposals?.[0]; if (saved) { try { setProposal(JSON.parse(saved.proposalJson)); setProposalId(saved.id); setLoading(false); return; } catch { /* Generate again. */ } } return fetch("/api/ai/integrate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ record, spaces: baseData.spaces, nodes: baseData.nodes }) }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "生成融合方案失败"); setProposal(data.result); }); }).catch((error) => setMessage(error instanceof Error ? error.message : "融合分析失败")).finally(() => setLoading(false)); }, [record]);
  const accepted = useMemo(() => proposal?.patches.filter((item) => item.accepted) || [], [proposal]); const affectedSpaces = useMemo(() => [...new Set(accepted.map((item) => item.targetSpaceId))], [accepted]);
  function updatePatch(id: string, values: Partial<PatchItem>) { setProposal((current) => current ? { ...current, patches: current.patches.map((item) => item.id === id ? { ...item, ...values } : item) } : current); }
  async function persist(action: "save" | "apply") { if (!proposal) return; setMessage(action === "apply" ? "正在把已勾选补丁写入镜像并发布新版本…" : "正在保存融合草稿…"); const response = await fetch("/api/integrations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, id: proposalId || undefined, recordId: record.id, proposal }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setMessage(data.error || "操作失败"); return; } if (action === "save") { setProposalId(data.proposal.id); setMessage("融合草稿已保存，尚未改变正式基座。"); } else { setMessage("融合完成：双向链接和新版本已经建立。"); window.setTimeout(onApplied, 900); } }
  if (loading) return <div className="integration-loading"><div className="analysis-orbit"><span /><i /></div><span className="eyebrow">COGNITIVE COMPILER</span><h1>正在判断这条记录会怎样改变你的体系…</h1><p>系统正在查重、寻找归属、识别冲突，并生成可撤销的基座补丁。</p></div>;
  if (!proposal) return <div className="card integration-error"><button className="back-button" onClick={onBack}>← 返回记录</button><h2>暂时无法生成融合方案</h2><p>{message}</p></div>;
  return <div className="integration-studio"><button className="back-button" onClick={onBack}>← 返回思维记录</button><header className="integration-hero"><div><span className="eyebrow">FROM RECORD TO SYSTEM · 融合工作台</span><h1>让一条记录，<br />真正改变你的体系。</h1><p>系统只提出建议。正式基座只会在你审阅并接受补丁后改变。</p></div><aside><span>推荐去向</span><strong>{proposal.destination}</strong><p>{proposal.why}</p></aside></header>
    <section className="integration-synthesis card"><div><span>记录</span><h2>{record.title}</h2><p>{record.source}</p></div><i>→</i><div><span>内化后的核心</span><h3>{proposal.synthesis}</h3><p>提炼出 {proposal.extractions.length} 个认知单元，形成 {proposal.patches.length} 项候选修改。</p></div></section>
    <nav className="integration-tabs"><button className={view === "patches" ? "active" : ""} onClick={() => setView("patches")}>01 审阅补丁</button><button className={view === "mirror" ? "active" : ""} onClick={() => setView("mirror")}>02 镜像对照</button><button className={view === "impact" ? "active" : ""} onClick={() => setView("impact")}>03 冲突与影响</button></nav>
    {view === "patches" && <section className="patch-review"><header><div><span className="eyebrow">PROPOSED PATCHES</span><h2>选择真正值得进入体系的变化</h2><p>你可以修改去向、标题和正文，也可以只接受一部分。</p></div><strong>{accepted.length} / {proposal.patches.length}</strong></header><div className="patch-list">{proposal.patches.map((patch, index) => <article className={`patch-card card ${patch.accepted ? "accepted" : ""}`} key={patch.id}><div className="patch-index"><button aria-label={patch.accepted ? "取消此补丁" : "接受此补丁"} onClick={() => updatePatch(patch.id, { accepted: !patch.accepted })}>{patch.accepted ? "✓" : ""}</button><span>PATCH {String(index + 1).padStart(2, "0")}</span><i>{patch.action.toUpperCase()}</i></div><div className="patch-fields"><label>写入哪个基座<select value={patch.targetSpaceId} onChange={(event) => updatePatch(patch.id, { targetSpaceId: event.target.value, targetNodeId: "" })}>{spaces.map((space) => <option value={space.id} key={space.id}>{space.kind === "meta" ? "元认知 · " : "领域 · "}{space.name}</option>)}</select></label><label>如何写入<select value={patch.action} onChange={(event) => updatePatch(patch.id, { action: event.target.value as PatchItem["action"] })}><option value="add">新增认知单元</option><option value="update">修改现有节点</option><option value="merge">与现有内容合并</option><option value="link">作为例证建立链接</option></select></label>{patch.action !== "add" && <label className="wide">目标节点<select value={patch.targetNodeId} onChange={(event) => { const node = nodes.find((item) => item.id === event.target.value); updatePatch(patch.id, { targetNodeId: event.target.value, currentContent: node?.content || "", title: node?.title || patch.title }); }}><option value="">请选择</option>{nodes.filter((node) => node.spaceId === patch.targetSpaceId).map((node) => <option value={node.id} key={node.id}>{node.title}</option>)}</select></label>}<label className="wide">认知单元名称<input value={patch.title} onChange={(event) => updatePatch(patch.id, { title: event.target.value })} /></label><label className="wide">建议写入内容<textarea value={patch.proposedContent} onChange={(event) => updatePatch(patch.id, { proposedContent: event.target.value })} /></label>{patch.playbookStep && <label className="wide playbook-patch">加入可执行流程的问题<textarea value={patch.playbookStep} onChange={(event) => updatePatch(patch.id, { playbookStep: event.target.value })} /></label>}</div><footer><div><strong>为什么建议这样改</strong><p>{patch.why}</p></div><div><strong>原文依据</strong><p>{patch.sourceEvidence}</p></div></footer></article>)}</div></section>}
    {view === "mirror" && <section className="mirror-workbench"><header><span className="eyebrow">SANDBOX MIRROR</span><h2>正式基座尚未改变</h2><p>左边是现在，右边是接受补丁后的镜像。所有变化都能追溯回这条记录。</p></header><div className="mirror-columns"><section><h3>当前基座</h3>{accepted.map((patch) => <article className="mirror-before" key={patch.id}><span>{spaces.find((space) => space.id === patch.targetSpaceId)?.name}</span><strong>{patch.title}</strong><p>{patch.currentContent || "这里目前没有对应内容。"}</p></article>)}</section><section><h3>融合后的镜像</h3>{accepted.map((patch) => <article className="mirror-after" key={patch.id}><span>＋ {patch.action === "add" ? "新增" : "修改"} · 双向链接</span><strong>{patch.title}</strong><p>{patch.proposedContent}</p>{patch.playbookStep && <small>流程新增：{patch.playbookStep}</small>}</article>)}</section></div></section>}
    {view === "impact" && <section className="integration-impact-grid"><article className="card"><span>提炼出的认知单元</span>{proposal.extractions.map((item) => <p key={item}>＋ {item}</p>)}</article><article className="card warning"><span>冲突与不确定性</span>{proposal.conflicts.length ? proposal.conflicts.map((item) => <p key={item}>△ {item}</p>) : <p>当前没有识别到明确冲突，但仍需你判断价值立场。</p>}</article><article className="card"><span>接受后会影响什么</span>{proposal.impact.map((item) => <p key={item}>→ {item}</p>)}</article></section>}
    <section className="integration-commit card"><div><strong>{accepted.length ? `准备更新 ${affectedSpaces.length} 个基座，写入 ${accepted.length} 项变化` : "尚未选择任何补丁"}</strong><span>应用后会自动生成新版本；原始记录、旧版本与修改依据全部保留。</span>{message && <p>{message}</p>}</div><div><button className="ghost-button" onClick={() => void persist("save")}>暂存融合草稿</button><button className="primary-button" disabled={!accepted.length} onClick={() => void persist("apply")}>接受补丁并发布新版本 →</button></div></section>
  </div>;
}
