"use client";

import { useEffect, useMemo, useState } from "react";

type RecordItem = { id: string; title: string; content: string; summary: string; primaryIssue: string; importance: number; nextReviewAt?: string | null; reviewCount: number };
type DigestItem = { id: string; title: string; excerpt: string; url: string; source: string; domain: string; publishedAt: string; reason: string };

export function TrainingHub({ records, onAnalyze }: { records: RecordItem[]; onAnalyze(text: string, focus: string): void }) {
  const [mode, setMode] = useState<"memory" | "today">("memory"); const [cursor, setCursor] = useState(0); const [digest, setDigest] = useState<DigestItem[]>([]); const [digestLoading, setDigestLoading] = useState(true); const [lensId, setLensId] = useState(""); const [selectedDigest, setSelectedDigest] = useState(0);
  const ranked = useMemo(() => [...records].sort((a, b) => { const overdueA = a.nextReviewAt && new Date(a.nextReviewAt) <= new Date() ? 10 : 0; const overdueB = b.nextReviewAt && new Date(b.nextReviewAt) <= new Date() ? 10 : 0; return (overdueB + b.importance * 2 - b.reviewCount) - (overdueA + a.importance * 2 - a.reviewCount); }), [records]);
  const recommended = ranked[cursor % Math.max(1, ranked.length)];
  useEffect(() => { fetch("/api/training-digest").then((response) => response.ok ? response.json() : null).then((data) => { if (data) setDigest(data.items || []); }).catch(() => undefined).finally(() => setDigestLoading(false)); }, []);
  async function grade(value: "again" | "hard" | "good" | "easy") { if (!recommended) return; await fetch("/api/records", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: recommended.id, action: "review", reviewGrade: value }) }); setCursor((value) => value + 1); }
  function analyzeDigest() { const article = digest[selectedDigest]; if (!article) return; const lens = records.find((record) => record.id === lensId); const text = lens ? `【要应用的既有思维记录】\n标题：${lens.title}\n重点：${lens.summary || lens.primaryIssue}\n原文：${lens.content}\n\n【今日材料】\n标题：${article.title}\n出处：${article.source}\n摘要：${article.excerpt}\n\n请先完整复原既有记录中的思路与重点，再把它作为分析透镜应用到今日材料；同时指出这一透镜可能造成的盲点。` : `标题：${article.title}\n出处：${article.source}\n摘要：${article.excerpt}`; onAnalyze(text, "整体分析"); }
  return <div className="training-hub"><header className="training-hub-head"><span className="eyebrow">DUAL PRACTICE · 双轨训练</span><h1>旧知回响，新事临场。</h1><p>一种训练让重要记录在该回来时回来；另一种训练把今天的新材料放上思维基座，练习真实判断。</p><div className="training-mode-switch"><button className={mode === "memory" ? "active" : ""} onClick={() => setMode("memory")}><span>01</span><strong>记忆复盘</strong><small>基于间隔与个人证据</small></button><button className={mode === "today" ? "active" : ""} onClick={() => setMode("today")}><span>02</span><strong>今日三篇</strong><small>论文、新闻与公共讨论</small></button></div></header>
    {mode === "memory" ? <section className="memory-practice card">{recommended ? <><div className="memory-reason"><span>为什么今天推荐它</span><p>{recommended.nextReviewAt && new Date(recommended.nextReviewAt) <= new Date() ? "它已经到达计划复习时间；" : "它尚未过期，但在当前档案中优先级较高；"}重要性为 {recommended.importance} 星，已复习 {recommended.reviewCount} 次。系统优先选择“重要、间隔已到、复习证据较少”的记录。</p></div><div className="memory-card"><small>RECALL WITHOUT LOOKING</small><h2>{recommended.title}</h2><p>先不打开原文：你还记得它最重要的结论、依据和一个可能的反例吗？</p><details><summary>翻开记录</summary><blockquote>{recommended.content}</blockquote><p>{recommended.summary}</p></details></div><div className="memory-actions"><button onClick={() => void grade("again")}>忘记了 · 明天</button><button onClick={() => void grade("hard")}>有点难 · 3 天</button><button onClick={() => void grade("good")}>记得 · 7 天</button><button onClick={() => void grade("easy")}>很熟 · 21 天</button></div><footer><button onClick={() => setCursor((value) => value + 1)}>跳过 / 换一条</button><button onClick={() => onAnalyze(recommended.content, recommended.primaryIssue || "整体分析")}>送入观照室深度复盘 →</button></footer></> : <p>先创建一条思维记录，系统才能为你安排复习。</p>}</section>
    : <section className="today-practice">{digestLoading && <div className="card digest-loading">正在从今日公开来源取回材料…</div>}{!digestLoading && digest.length === 0 && <div className="card digest-loading">今天的外部来源暂时没有可用内容，请稍后刷新。</div>}<div className="digest-grid">{digest.map((item, index) => <article className={`digest-card card ${selectedDigest === index ? "active" : ""}`} key={item.id} onClick={() => setSelectedDigest(index)}><div><span>{item.domain}</span><small>{new Date(item.publishedAt).toLocaleDateString("zh-CN", { month: "short", day: "numeric" })}</small></div><h2>{item.title}</h2><p>{item.excerpt}</p><strong>选择理由</strong><blockquote>{item.reason}</blockquote><a href={item.url} target="_blank" rel="noreferrer">阅读原文 ↗</a></article>)}</div>{digest.length > 0 && <div className="lens-application card"><div><span className="eyebrow">APPLY A LENS</span><h2>用一条既有记录，照向今日材料</h2><p>系统会先复原旧记录的重点和推理方式，再将它应用到所选材料，并主动检查这副“透镜”的盲区。</p></div><label>选择思维记录<select value={lensId} onChange={(event) => setLensId(event.target.value)}><option value="">不使用旧记录，只做体系分析</option>{records.map((record) => <option value={record.id} key={record.id}>{record.title}</option>)}</select></label><button className="primary-button" onClick={analyzeDigest}>进入观照室分析并生成问题 →</button></div>}</section>}
  </div>;
}
